language: bash

services: docker

env:
  - VERSION=7.3 VARIANT=alpine

before_script:
  - docker login "$PDHUSER}" "${DHTOKEN}"
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="mihard/php-with-unit:${VERSION}-${VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      docker push "$image"
    )

after_script:
  - docker images
  - docker tag mihard/php-with-unit:7.3-alpine mihard/php-with-unit:latest
  - docker push mihard/php-with-unit:latest